# spring整合配置
spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menu?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8
    username: ljf
    password: ljf
    # 使用druid连接池，当使用其他连接池的时候，可以指定type类型为对应的数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      maxActive: 1000
      initialSize: 10
      maxWait: 1000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxPoolPreparedStatementPerConnectionSize: 0
      # 监控
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow: 127.0.0.1
      web-stat-filter:
        url-pattern: /*
        exclusions: /druid/*,*.js,*.css,*.html,*.png,*.jpg
# mybatis配置
mybatis:
  type-aliases-package: edu.nf.ch06.entity
  mapper-locations: classpath:/mapper/*.xml
# 分页插件配置
pagehelper:
  # 数据库方言
  helper-dialect: mysql
  # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页
  reasonable: true
  # 分页参数注解支持
  support-methods-arguments: true